package com.duyi.onlinevideo.entity;

/**
 * tools_item
 * 
 * @author bianj
 * @version 1.0.0 2020-09-16
 */
public class ToolsItem implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 5395125227466483893L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer id;

    /** name */
    private String name;

    /** toolsUrl */
    private String toolsUrl;

    /** iconUrl */
    private String iconUrl;

    /** toolsTypeId */
    private Integer toolsTypeId;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取name
     * 
     * @return name
     */
    public String getName() {
        return this.name;
    }

    /**
     * 设置name
     * 
     * @param name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 获取toolsUrl
     * 
     * @return toolsUrl
     */
    public String getToolsUrl() {
        return this.toolsUrl;
    }

    /**
     * 设置toolsUrl
     * 
     * @param toolsUrl
     */
    public void setToolsUrl(String toolsUrl) {
        this.toolsUrl = toolsUrl;
    }

    /**
     * 获取iconUrl
     * 
     * @return iconUrl
     */
    public String getIconUrl() {
        return this.iconUrl;
    }

    /**
     * 设置iconUrl
     * 
     * @param iconUrl
     */
    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
    }

    /**
     * 获取toolsTypeId
     * 
     * @return toolsTypeId
     */
    public Integer getToolsTypeId() {
        return this.toolsTypeId;
    }

    /**
     * 设置toolsTypeId
     * 
     * @param toolsTypeId
     */
    public void setToolsTypeId(Integer toolsTypeId) {
        this.toolsTypeId = toolsTypeId;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}